#!/bin/bash

echo "📝 Updating Twitter Credentials..."
echo "================================"
echo ""
echo "Please update your .env.local file with these new credentials:"
echo ""
echo "TWITTER_CLIENT_ID=UXo4X1ZVakFDTHUyNVNBUXl6Mzc6MTpjaQ"
echo "TWITTER_CLIENT_SECRET=-DbmLslP-CvxEVz36ic-C6lR9FsjT5uoAOV1mSu420mEFuJ42r"
echo "TWITTER_BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAHZc0gEAAAAAsmabcB%2Figo73dcX5pp8UZM%2FHa24%3D5ScqeCvqzrjPuTFzdH1rrwxNlttfJov1qTxCijE5vjXGR9z3ZH"
echo ""
echo "After updating, you need to:"
echo "1. Restart your local dev server (Ctrl+C and npm run dev)"
echo "2. Update these same credentials in Vercel Dashboard"
echo "3. Redeploy your Vercel app"
echo ""
echo "To update in Vercel:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select 'kol-test' project"
echo "3. Go to Settings → Environment Variables"
echo "4. Update TWITTER_CLIENT_ID, TWITTER_CLIENT_SECRET, and TWITTER_BEARER_TOKEN"
echo "5. Click Save and Redeploy" 