#!/bin/bash

echo "🚀 Deploying KOL Platform to Test Environment"
echo "============================================"
echo ""
echo "This will create a new Vercel project called 'kol-test'"
echo "without affecting your production 'kol' project."
echo ""
echo "Prerequisites:"
echo "1. Make sure you have Vercel CLI installed (npm i -g vercel)"
echo "2. Be logged into Vercel (vercel login)"
echo ""
read -p "Press Enter to continue..."

# Deploy using the test configuration
echo ""
echo "📦 Starting deployment..."
vercel --prod -c vercel-test.json --yes

echo ""
echo "🎯 After deployment completes:"
echo ""
echo "1. Go to your Vercel dashboard"
echo "2. Find the 'kol-test' project"
echo "3. Go to Settings → Environment Variables"
echo "4. Add these variables from your production project:"
echo ""
echo "   TWITTER_CLIENT_ID"
echo "   TWITTER_CLIENT_SECRET" 
echo "   NEXTAUTH_URL (use your test domain like https://kol-test.vercel.app)"
echo "   NEXTAUTH_SECRET"
echo "   TWITTER_BEARER_TOKEN"
echo "   REDIS_URL (same as production - this shares the database)"
echo "   SMTP_HOST"
echo "   SMTP_PORT"
echo "   SMTP_USER"
echo "   SMTP_PASS"
echo "   SMTP_FROM"
echo ""
echo "5. Redeploy after adding environment variables"
echo ""
echo "⚠️  Important: Update NEXTAUTH_URL to match your test domain!" 